<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Optimus.Contracts\Optimus.Contracts.csproj" />
    <ProjectReference Include="..\Optimus.Core\Optimus.Core.csproj" />
  </ItemGroup>
</Project>
