<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Optimus.Contracts\Optimus.Contracts.csproj" />
    <ProjectReference Include="..\Optimus.Core\Optimus.Core.csproj" />
    <ProjectReference Include="..\Optimus.Inference\Optimus.Inference.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Optimus.Core.Tests" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
